[package]
name = "echor"
version = "0.1.0"
author = "nt2311-vn"
about = "Rust echo"
edition = "2024"

[dependencies]
clap = {version = "4.5.51", features = ["derive"]}

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
