[package]
name = "headr"
version = "0.1.0"
edition = "2024"
authors = ["nt2311-vn"]

[dependencies]
clap = {version = "4.5.0", features = ["derive"]}
anyhow = "1"

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
rand = "0.8"
pretty_assertions = "1"
