[package]
name = "catr"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.5.51", feature = ["derive"]}
anyhow = "1.0.100"

[dev-dependencies]
assert_cmd = "2"
predicates = "2"
rand = "0.8"
